### ISSUE TITLE
Custom Notification to Slack

### ISSUE THREAD

**Issue by kardasio** [IBM-UrbanCode/Slack-UCD#5]
When I'm trying to run the step "Post Custom Notification to Slack"  it always throws the error 

`
Caught: java.lang.ClassCastException: java.lang.String incompatible with java.lang.Integer
java.lang.ClassCastException: java.lang.String incompatible with java.lang.Integer
at postToSlackCustom.run(postToSlackCustom.groovy:33)
`

So that is the line -   
`attachmentJson.content[0].ts = "" + System.currentTimeMillis()/1000;`   
in the postToSlackCustom.groovy file.

It should work in Java  as well as String.valueOf(System.currentTimeMillis()/1000), but it seems to be the groovy script which I'm not familiar with.

Could you please sort it out? 

Thanks

**Comment by nhmathis** [comment]
@kardasio, I've tried this quickly in a Groovy shell script and this line seems to resolve correctly. I'll need to dive into actually recreating the bug. 

@tlawrie, This bug may simply be caused by a different version of Groovy or Java. Do you have any insight on this bug? Any suggestions of what value the attachment property should be?

-Nick

**Comment by nhmathis** [comment]
I believe attachment is supposed to take this structure: https://api.slack.com/docs/message-attachments

Note the Attachment Structure example.

**Comment by kardasio** [comment]
@nhmathis as the attachment I used something simple like 
`{ "text": "test" }`
you can validate it [here](https://api.slack.com/docs/messages/builder?msg=%7B%22text%22%3A%20%22This%20is%20a%20line%20of%20text.%5CnAnd%20this%20is%20another%20one.%22%7D)

**Comment by nhmathis** [comment]
Through some additional investigation I've discovered that the `Post Custom Notification to Slack` is actually a Post Attachment Notification to Slack step.

[You can use this attachment creation tool to get it working asap](https://api.slack.com/docs/messages/builder?msg=%7B%22attachments%22%3A%5B%7B%22fallback%22%3A%22Required%20plain-text%20summary%20of%20the%20attachment.%22%2C%22color%22%3A%22%2336a64f%22%2C%22pretext%22%3A%22Optional%20text%20that%20appears%20above%20the%20attachment%20block%22%2C%22author_name%22%3A%22Bobby%20Tables%22%2C%22author_link%22%3A%22http%3A%2F%2Fflickr.com%2Fbobby%2F%22%2C%22author_icon%22%3A%22http%3A%2F%2Fflickr.com%2Ficons%2Fbobby.jpg%22%2C%22title%22%3A%22Slack%20API%20Documentation%22%2C%22title_link%22%3A%22https%3A%2F%2Fapi.slack.com%2F%22%2C%22text%22%3A%22Optional%20text%20that%20appears%20within%20the%20attachment%22%2C%22fields%22%3A%5B%7B%22title%22%3A%22Priority%22%2C%22value%22%3A%22High%22%2C%22short%22%3Afalse%7D%5D%2C%22image_url%22%3A%22http%3A%2F%2Fmy-website.com%2Fpath%2Fto%2Fimage.jpg%22%2C%22thumb_url%22%3A%22http%3A%2F%2Fexample.com%2Fpath%2Fto%2Fthumb.png%22%2C%22footer%22%3A%22Slack%20API%22%2C%22footer_icon%22%3A%22https%3A%2F%2Fplatform.slack-edge.com%2Fimg%2Fdefault_application_icon.png%22%2C%22ts%22%3A123456789%7D%5D%7D)

However, you will need to update the word `attachments` to `content`. This is a defect in the plugin and one that would otherwise have been unknown to the user. I'll will be making some updates to the plugin to get around this issue...

Intended Updates: 
1. Change the name of the plugin step to `Post Attachment Notification to Slack`
2. Expect (and null check) for the word `attachments` instead of `content`
3. Adding timestamp to all found attachments

This update should be released later today. However, if you would just like to post a simple message to slack, try out the  `Post Notification to Slack`.

**Comment by nhmathis** [comment]
Created a pull request #6 that should resolve this issue.

**Comment by tlawrie** [comment]
Hi Nick,

You are correct. This is really a Post Attachment Notification to Slack.

Thanks,
Tyson

**Comment by nhmathis** [comment]
Version 4 of the plugin has been released. Should resolve this issue. Please use the example in the above comment. If it fails, it will try to alert you and give a quick example. 

let me know if you have any issues.

**Comment by kardasio** [comment]
Thank you @nhmathis , @tlawrie 
It does work
