### ISSUE TITLE
Slack integration when using an Application Template

### ISSUE THREAD

**Issue by stephet3** [IBM-UrbanCode/Slack-UCD#7]
Is there an issue with using this plugin when using ucd application templates?  If I try to configure the notification to slack in an Application template, it completes but does nothing.  In the status column it reads "No Version Selected".  If I do not use an Application Template and just setup the processes directly --- it seems to work.  I am just wondering if this is suppose to work when the application is setup using an application template with the notification step as part of that template.

**Comment by nhmathis** [comment]
Hi @stephet3,

The `No Version Selected` is more of a component process configuration issue, rather than Slack plugin specific. The default component processes take on the `Deployment` type. This configuration, when specified in an application process, will expect you to specify a component version at deploy time. If none is specified, then you'll see the `No Version Selected` issue. [Here you can see all of the component process types explained fully.](https://www.ibm.com/support/knowledgecenter/SS4GSP_6.2.6/com.ibm.udeploy.doc/topics/comp_process_types.html) 

However, if you configure your component process as `Operational (No Version Needed)`, you will not need to specify a version and the Slack step will run as expected. Otherwise, add a dummy component version to your component and select it at deploy time.

Your second test approach of running this Slack step in a generic step is always what I recommend. Generic Processes typically allow you to test processes and step much more quickly than a full Application Process.

Hope this helps!

**Comment by stephet3** [comment]
The application template does indeed have components associated with it.  There is an install application process that has a subprocess that gets ran on every agent.  We are trying to use the slack notification to report on a ucd deploy.  When I run the application, the application is indeed installed, the application env inventory is updated, but the notification step does not send anything giving the "No Version Selected".  If I recreate the application without using the template but defining the process specific for that application --- the slack notification happens.  So has this been tested using an application template?
<img width="1145" alt="image" src="https://user-images.githubusercontent.com/29008416/32228018-5c086a8e-be23-11e7-8ca8-b1661f9a821f.png">

**Comment by nhmathis** [comment]
Hi,

I still do not believe that this a Slack plugin issue. Try replacing the Slack step in the component process with a different step, do you see the same error?

Does the component process step(s) specified in the `Slack - X Notification` steps have the process type of `Operational (No Version Needed)`. For example: 
![image](https://user-images.githubusercontent.com/14111822/32233724-6f974e40-be31-11e7-9a5d-47ddab8f81cf.png)

If so, then this is a UCD configuration bug and you should be able to file an APAR.

**Comment by stephet3** [comment]
So I did see I had failed to change the Process type on the Slack - X Notification steps --- they were set to Deployment.  I changed these to Operational(No Version Needed) and now the process at least runs --- still fails though.  It fails saying that ${p:version.name} is unresolved.  The "Stop WLP Service + Install WLP Service Application" step in the above process is set to Deployment all others are Operational(No Version Needed) steps.  So how is this slack step suppose to get the version from that step?

**Comment by stephet3** [comment]
Okay, so looking at the properties for that step when executing and I do not see a version.name.  I see a currentVersion.name and a previousVersion.name.  I changed step to look for ${p:currentVersion.name} and it appears to work I need to test some more.  Is it possible that the default value for this is no longer valid?

**Comment by stephet3** [comment]
Okay, I missed it.  It is listed as a property --- so not sure why it says it is undefined if currentVersion.name works

**Comment by stephet3** [comment]
To be clear, the version.name is available on the deploy step but if I list all the properties the slack step knows about --- version.name is not one of them.  So on a success, currentVersion.name works just fine.  On a failure though, I need the version that failed not the currentVersion.name or previousVersion.name.  I am trying to figureout how to promote the version.name to a component level property

**Comment by nhmathis** [comment]
`version.name` is resolved automagically when you run a component process that requires a version. Because `Operational (No Version Needed)` does not use a version, you you'll see that `${p:version.name}` does not get resolved. However, you can implement you own property based on the component specified or simply leave it blank. If you want to retrieve version information, you'll need to add the Slack process to a process that requires a version. The easiest way would be to add this to your For Each Agent loop. 

Another approach is using `Install Multiple Components` app process. This will take the version information and be able to resolve the `version.name` property. However, with this approach you will run it once for each version you run it against.

Furthermore, if you simply replace the Slack operational processes with Install Multiple Components, it will run X number of times based on the overall success of the For Each Agent loop. For example, if you have 3 agent processesand 1 of them fails, you current logic will follow the failure path. Then, if you then use my `Install Multiple Components` suggested approach, each version will report a failure regardless of the agent's true result. Because there is not a summary slack message (unless you generate the logic to do so), the Slack message will run on a per-version basis. For that reason, I suggest you add the slack message logic within your For Each Agent loop.

**Comment by stephet3** [comment]
Okay,  so I have been able to get this to work as suggested.  The issue we
now see using the install multiple Components procedure is that when the
install fails and it follows the failure path,  when the post to slack
completes it updates the resource to the new version even though the
version failed.  This is due to the fact the slack post is an install
process.  This seems less then optimal.

Todd Stephens

On Nov 7, 2017 14:32, "Nick Mathison" <notifications@github.com> wrote:

version.name is resolved automagically when you run a component process
that requires a version. Because Operational (No Version Needed) does not
use a version, you you'll see that ${p:version.name} does not get resolved.
However, you can implement you own property based on the component
specified or simply leave it blank. If you want to retrieve version
information, you'll need to add the Slack process to a process that
requires a version. The easiest way would be to add this to your For Each
Agent loop.

Another approach is using Install Multiple Components app process. This
will take the version information and be able to resolve the version.name
property. However, with this approach you will run it once for each version
you run it against.

Furthermore, if you simply replace the Slack operational processes with
Install Multiple Components, it will run X number of times based on the
overall success of the For Each Agent loop. For example, if you have 3
agent processesand 1 of them fails, you current logic will follow the
failure path. Then, if you then use my Install Multiple Components
suggested approach, each version will report a failure regardless of the
agent's true result. Because there is not a summary slack message (unless
you generate the logic to do so), the Slack message will run on a
per-version basis. For that reason, I suggest you add the slack message
logic within your For Each Agent loop.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/IBM-UrbanCode/Slack-UCD/issues/7#issuecomment-342595818>,
or mute the thread

**Comment by nhmathis** [comment]
Simple change. 

After the `Slack-Failure Notification`, instead of continuing to the `Finish` box, use the `Set Status` step. This step can specify a `Failed` result and properly exit your process.

**Comment by stephet3** [comment]
Hmmmm,  I use the set state step so the application deploy process does
show that it failed.  The issue though is that since the slack step is a
deploy process and it completes,  it updates the resource tree inventory to
that new version even though that version failed to deploy.  So the env
does not show out of compliance because the resource shows as updated to
the version the env  inventory was updated to.

Todd Stephens

**Comment by stephet3** [comment]
Do I need to work the slack notifications into the component process for
the deploy processes so that none of the slack steps need to be separate
deploy processes?

Todd Stephens

**Comment by mathison42** [comment]
The Slack step was intended for a component process. However, the `Attachment Notification` Slack step can take any form.

Does your application process still look like the picture above? If not, would you mind posting it again? If  you post to slack message is a `Deployment` process, it will record the inventory as a success. Otherwise, if they are `Operational (No Version Needed)` then it should be working as expected. 

Running it as a Generic Process, instead of a component process, may be a possible solution as well.

**Comment by nhmathis** [comment]
The Slack step was intended for a component process. However, the Attachment Notification Slack step can take any form.

Does your application process still look like the picture above? If not, would you mind posting it again? If you post to slack message is a Deployment process, it will record the inventory as a success. Otherwise, if they are Operational (No Version Needed) then it should be working as expected.

Running it as a Generic Process, instead of a component process, may be a possible solution as well.

**Comment by stephet3** [comment]
Okay I am beginning to get somewhere now.  I have moved the slack
notification in the deploy component process instead of in the application
process.  This seems to make life a little easier.  Now I am running into
issues with the emoji.  In the application process I have three deploy
components each with its own slack notification step.  When you execute the
ucd application,  only the first notification displays its emoji,  all
follow on notifications get no emoji till the application process
completes.  Is there a way to make each notification get its own emoji or
is this an issue with slack?

Todd Stephens

**Comment by nhmathis** [comment]
This is a Slack issue where quick, subsequent comments will share the same comment tile. You may be able to get around this issue with the other `Attachment Notification` step. However, you will need to write the main body of the Slack message. [That documentation can be found here.](https://api.slack.com/docs/message-attachments) Specifically the `Attachment structure` section.
